PUT https://localhost:7190/transaction/fundTransfer
Content-Type: application/json

{
    "sourceAccountNumber" : "41452119",
    "destinationAccountNumber" : "79697980",
    "sourceAccountPassword": "Pass@123",
    "amount" : 100.00
}
